In [4]:
#%pip install numpy
#%pip install comet_ml
#%pip install tensorflow[and-cuda]
#%pip install matplotlib
#%pip install pyyaml h5py
#import comet_ml as ml
import tensorflow as tf
import keras
from keras import layers
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.image import imread
import numpy as np
import sys
import os
from PIL import Image

In [ ]:
API_KEY = 'xUELgBjS6eWY8xy6DBOOJS6Dj'

In [ ]:
#SKIP OLD Code



#SKIP OLD CODE
#IMAGE_SIZE = 150
IMAGE_LAYERS = 3
IMAGE_NUMBERS = 325
IMAGE_CATEGORIES = 3
TEST_IMAGE_NUMBERS = 25

labels = np.zeros(shape=(IMAGE_NUMBERS * IMAGE_CATEGORIES,), dtype='int64')
train_images = np.zeros(shape=(IMAGE_NUMBERS * IMAGE_CATEGORIES, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS), dtype='float32')
for i in range(0, IMAGE_NUMBERS - 1):
    train_images[i] = imread("A_img" + str((i+1)) + ".png")
    labels[i] = 0
    #train_images[i + IMAGE_NUMBERS] = imread("B_img" + str((i+1)) + ".png")
    #labels[i + IMAGE_NUMBERS] = 1 
    #train_images[i + IMAGE_NUMBERS * 2] = imread("C_img" + str((i+1)) + ".png")
    #labels[i + IMAGE_NUMBERS * 2] = 0
    train_images[i + IMAGE_NUMBERS * 3] = imread("D_img" + str((i+1)) + ".png")
    labels[i + IMAGE_NUMBERS * 3] = 1
    train_images[i + IMAGE_NUMBERS * 4] = imread("E_img" + str((i+1)) + ".png")
    labels[i + IMAGE_NUMBERS * 4] = 2
    #train_images[i + IMAGE_NUMBERS * 5] = imread("F_img" + str((i+1)) + ".png")
    #labels[i + IMAGE_NUMBERS * 5] = 2

testing_labels = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES,), dtype='int64')
testing_images = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS), dtype='float32')
for i in range(0, TEST_IMAGE_NUMBERS - 1):
    testing_images[i] = imread("A_img" + str((i+1)) + ".png")
    testing_labels[i] = 0
    #testing_images[i + TEST_IMAGE_NUMBERS] = imread("B_img" + str((i+1)) + ".png")
    #testing_labels[i + TEST_IMAGE_NUMBERS] = 1
    #testing_images[i + TEST_IMAGE_NUMBERS * 2] = imread("C_img" + str((i+1)) + ".png")
    #testing_labels[i + TEST_IMAGE_NUMBERS * 2] = 0
    testing_images[i + TEST_IMAGE_NUMBERS * 3] = imread("D_img" + str((i+1)) + ".png")
    testing_labels[i + TEST_IMAGE_NUMBERS * 3] = 1
    testing_images[i + TEST_IMAGE_NUMBERS * 4] = imread("E_img" + str((i+1)) + ".png")
    testing_labels[i + TEST_IMAGE_NUMBERS * 4] = 2
    #testing_images[i + TEST_IMAGE_NUMBERS * 5] = imread("F_img" + str((i+1)) + ".png")
    #testing_labels[i + TEST_IMAGE_NUMBERS * 5] = 2
plt.imshow(train_images[4])
plt.imshow(train_images[305])

In [2]:
ORGINAL_IMAGE_SIZE = 150
IMAGE_SIZE = 125
IMAGE_LAYERS = 3
IMAGE_NUMBERS = 325
IMAGE_CROPINGS = 10
IMAGE_CATEGORIES = 6
TEST_IMAGE_NUMBERS = 25


labels = np.zeros(shape=(IMAGE_NUMBERS * IMAGE_CATEGORIES * IMAGE_CROPINGS,), dtype='int64')
train_images = np.zeros(shape=(IMAGE_NUMBERS * IMAGE_CATEGORIES * IMAGE_CROPINGS, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS), dtype='int64')
train_images_array = [None] * (IMAGE_NUMBERS * IMAGE_CATEGORIES)
labels_array = [None] * (IMAGE_NUMBERS * IMAGE_CATEGORIES)
for i in range(0, IMAGE_NUMBERS):
    train_images_array[i] = Image.open("A_img" + str((i+1)) + ".png")
    labels_array[i] = 0
    train_images_array[i + IMAGE_NUMBERS] = Image.open("B_img" + str((i+1)) + ".png")
    labels_array[i + IMAGE_NUMBERS] = 1 
    train_images_array[i + IMAGE_NUMBERS * 2] = Image.open("C_img" + str((i+1)) + ".png")
    labels_array[i + IMAGE_NUMBERS * 2] = 2
    train_images_array[i + IMAGE_NUMBERS * 3] = Image.open("D_img" + str((i+1)) + ".png")
    labels_array[i + IMAGE_NUMBERS * 3] = 3
    train_images_array[i + IMAGE_NUMBERS * 4] = Image.open("E_img" + str((i+1)) + ".png")
    labels_array[i + IMAGE_NUMBERS * 4] = 4
    train_images_array[i + IMAGE_NUMBERS * 5] = Image.open("F_img" + str((i+1)) + ".png")
    labels_array[i + IMAGE_NUMBERS * 5] = 5

for i in range(0, IMAGE_NUMBERS * IMAGE_CATEGORIES):
    train_images[IMAGE_CROPINGS * i] = train_images_array[i].crop((0, 0, IMAGE_SIZE, IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 1] = train_images_array[i].crop((ORGINAL_IMAGE_SIZE - IMAGE_SIZE, 0, ORGINAL_IMAGE_SIZE, IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 2] = train_images_array[i].crop((0, ORGINAL_IMAGE_SIZE - IMAGE_SIZE, IMAGE_SIZE, ORGINAL_IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 3] = train_images_array[i].crop((ORGINAL_IMAGE_SIZE - IMAGE_SIZE, ORGINAL_IMAGE_SIZE - IMAGE_SIZE, ORGINAL_IMAGE_SIZE, ORGINAL_IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 4] = train_images_array[i].crop((int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2)))
    train_images[(IMAGE_CROPINGS * i) + 5] = train_images_array[i].resize((IMAGE_SIZE, IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 6] = train_images_array[i].crop((0, 
                                                                         int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         IMAGE_SIZE, 
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2)))
    train_images[(IMAGE_CROPINGS * i) + 7] = train_images_array[i].crop((ORGINAL_IMAGE_SIZE - IMAGE_SIZE, 
                                                                         int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2),
                                                                         ORGINAL_IMAGE_SIZE,
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2)))
    train_images[(IMAGE_CROPINGS * i) + 8] = train_images_array[i].crop((int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         0, 
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         IMAGE_SIZE))
    train_images[(IMAGE_CROPINGS * i) + 9] = train_images_array[i].crop((int((ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         ORGINAL_IMAGE_SIZE - IMAGE_SIZE, 
                                                                         int(ORGINAL_IMAGE_SIZE - (ORGINAL_IMAGE_SIZE - IMAGE_SIZE)/2), 
                                                                         ORGINAL_IMAGE_SIZE))
    
    for j in range(0, IMAGE_CROPINGS):
        labels[(IMAGE_CROPINGS * i) + j] = labels_array[i]

testing_labels = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES * 4,), dtype='int64')
testing_images = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES * 4, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS), dtype='int64')
testing_labels_array = [None] * (TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES)
testing_images_array = [None] * (TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES)
for i in range(0, TEST_IMAGE_NUMBERS):
    testing_images_array[i] = Image.open("A_img" + str((i+326)) + ".png")
    testing_labels_array[i] = 0
    testing_images_array[i + TEST_IMAGE_NUMBERS] = Image.open("B_img" + str((i+326)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS] = 1
    testing_images_array[i + TEST_IMAGE_NUMBERS * 2] = Image.open("C_img" + str((i+326)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 2] = 2
    testing_images_array[i + TEST_IMAGE_NUMBERS * 3] = Image.open("D_img" + str((i+326)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 3] = 3
    testing_images_array[i + TEST_IMAGE_NUMBERS * 4] = Image.open("E_img" + str((i+326)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 4] = 4
    testing_images_array[i + TEST_IMAGE_NUMBERS * 5] = Image.open("F_img" + str((i+326)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 5] = 5

for i in range(0, TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES):
    testing_images[4 * i] = testing_images_array[i].crop((0, 0, IMAGE_SIZE, IMAGE_SIZE))
    testing_images[(4 * i) + 1] = testing_images_array[i].crop((ORGINAL_IMAGE_SIZE - IMAGE_SIZE, 0, ORGINAL_IMAGE_SIZE, IMAGE_SIZE))
    testing_images[(4 * i) + 2] = testing_images_array[i].crop((0, ORGINAL_IMAGE_SIZE - IMAGE_SIZE, IMAGE_SIZE, ORGINAL_IMAGE_SIZE))
    testing_images[(4 * i) + 3] = testing_images_array[i].crop((ORGINAL_IMAGE_SIZE - IMAGE_SIZE, ORGINAL_IMAGE_SIZE - IMAGE_SIZE, ORGINAL_IMAGE_SIZE, ORGINAL_IMAGE_SIZE))
    testing_labels[4 * i] = testing_labels_array[i]
    testing_labels[(4 * i) + 1] = testing_labels_array[i]
    testing_labels[(4 * i) + 2] = testing_labels_array[i]
    testing_labels[(4 * i) + 3] = testing_labels_array[i]

In [55]:
testing_labels_array = [None] * (TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES)
testing_images_array = [None] * (TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES)
for i in range(0, TEST_IMAGE_NUMBERS):
    testing_images_array[i] = Image.open("A_img" + str((i+1)) + ".png")
    testing_labels_array[i] = 0
    testing_images_array[i + TEST_IMAGE_NUMBERS] = Image.open("B_img" + str((i+1)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS] = 1
    testing_images_array[i + TEST_IMAGE_NUMBERS * 2] = Image.open("C_img" + str((i+1)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 2] = 2
    testing_images_array[i + TEST_IMAGE_NUMBERS * 3] = Image.open("D_img" + str((i+1)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 3] = 3
    testing_images_array[i + TEST_IMAGE_NUMBERS * 4] = Image.open("E_img" + str((i+1)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 4] = 4
    testing_images_array[i + TEST_IMAGE_NUMBERS * 5] = Image.open("F_img" + str((i+1)) + ".png")
    testing_labels_array[i + TEST_IMAGE_NUMBERS * 5] = 5

for i in range(0, TEST_IMAGE_NUMBERS):
    testing_images[4 * i] = testing_images_array[i].crop((0, 0, 100, 100))
    testing_images[(4 * i) + 1] = testing_images_array[i].crop((50, 0, 150, 100))
    testing_images[(4 * i) + 2] = testing_images_array[i].crop((0, 50, 100, 150))
    testing_images[(4 * i) + 3] = testing_images_array[i].crop((50, 50, 150, 150))
    testing_labels[4 * i] = testing_labels_array[i]
    testing_labels[(4 * i) + 1] = testing_labels_array[i]
    testing_labels[(4 * i) + 2] = testing_labels_array[i]
    testing_labels[(4 * i) + 3] = testing_labels_array[i]

In [10]:
img = Image.open("A_img" + str(1) + ".png")
#croppedImage = img.crop((0, 0, 100, 100))
#croppedImage = img.crop((50, 50, 150, 150))
#croppedImage = croppedImage.resize((150,150))
#plt.imshow(croppedImage)
resized = np.zeros(shape=(1, 125, 125, 3), dtype='int64')
resized[0] = img.resize((125, 125))
np.set_printoptions(threshold=sys.maxsize)
f = open("imageDataExample.txt", 'w')
print(repr(resized[0]), file=f)
np.set_printoptions(threshold=10)
print(resized[0])
#x = testing_images_array[20].crop((0,0, 100, 100))
#plt.imshow(train_images[900])
#print(train_images_array[224].crop((0, 0, 100, 100)))
#print(labels)
#print(train_images[900])

[[[  7 178 234]
  [  9 179 235]
  [ 13 180 234]
  ...
  [  0 161 229]
  [  0 161 229]
  [  0 161 229]]

 [[  9 177 234]
  [ 11 179 235]
  [ 14 180 234]
  ...
  [  0 161 229]
  [  0 161 229]
  [  0 161 229]]

 [[ 11 176 234]
  [ 13 178 235]
  [ 16 179 236]
  ...
  [  0 161 229]
  [  0 161 229]
  [  0 161 229]]

 ...

 [[129 205 241]
  [129 205 241]
  [129 205 241]
  ...
  [133 200 243]
  [133 200 243]
  [133 200 243]]

 [[129 205 241]
  [129 205 241]
  [129 205 241]
  ...
  [132 199 242]
  [132 199 242]
  [132 199 242]]

 [[129 205 241]
  [129 205 241]
  [129 205 241]
  ...
  [131 198 241]
  [131 198 241]
  [131 198 241]]]


In [6]:
FIRSTLAYERS = 2
SECONDLAYERS = 2

FILTERSSTART = 28

FILTERSIZE = (10, 10)
FILTERTWOSIZE = (9, 9)

FILTERSTRIDES = (2, 2)
FILTERTWOSTRIDES = (5, 5)

In [1]:
def generate_CNN():
    #model = tf.keras.Sequential([
    #    keras.layers.Input(shape=(150, 150, 3)),
    #    keras.layers.Conv2D(64, (10, 10), strides=(2, 2), padding='same'),
    #    keras.layers.LeakyReLU(),
    #
    #    keras.layers.Conv2D(64, (7, 7), strides=(2, 2), padding='same'),
    #    keras.layers.LeakyReLU(),
    #
    #    keras.layers.Conv2D(128, (10, 10), strides=(5, 5), padding='same'),
    #    keras.layers.LeakyReLU(),
    #    keras.layers.Flatten(),
    #    keras.layers.Dense(6, activation='sigmoid'),
    #    keras.layers.Dense(6, activation='softmax')
    #])
    model = tf.keras.Sequential()
    model.add(keras.layers.Input(shape=(IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS)))
    for i in range(0, FIRSTLAYERS):
        model.add(keras.layers.Conv2D(int(FILTERSSTART + i * FILTERSSTART / 2), FILTERSIZE, FILTERSTRIDES, padding='same'))
        model.add(keras.layers.LeakyReLU())
    
    for i in range(0, SECONDLAYERS):
        model.add(keras.layers.Conv2D(FILTERSSTART + i * FILTERSSTART + FILTERSSTART * FIRSTLAYERS, FILTERSTRIDES, padding='same'))
        model.add(layers.LeakyReLU())
    
    model.add(keras.layers.Flatten())
    model.add(keras.layers.Dense(IMAGE_CATEGORIES, activation='softmax'))
    return model

In [2]:
LEARNING_RATE = 1e-5
BATCH_SIZE = 325
EPOCHS = 27

model1 = generate_CNN()
print(model1.output_shape)

NameError: name 'tf' is not defined

In [47]:
#print(train_images[0][0][0][1])
#for i in range(1300, 1949):
#    for f in range(0, 2):
#        print(train_images[i][0][0][f])
#print(Image.open())

0.69803923
0.14117648
0.14509805
0.047058824
0.06666667
0.07450981
0.11764706
0.08235294
0.1254902
0.36862746
0.4
0.03529412
0.039215688
0.1254902
0.14509805
0.5647059
0.5803922
0.5803922
0.59607846
0.3254902
0.34509805
0.2627451
0.3137255
0.4392157
0.50980395
0.003921569
0.015686275
0.70980394
0.78039217
0.73333335
0.75686276
0.03529412
0.050980393
0.07450981
0.078431375
0.07058824
0.09803922
0.08235294
0.09411765
0.050980393
0.07450981
0.023529412
0.023529412
0.0
0.011764706
0.4117647
0.47058824
0.0
0.019607844
0.07450981
0.11372549
0.07450981
0.11372549
0.21568628
0.25490198
0.2627451
0.25882354
0.21568628
0.25490198
0.15294118
0.19215687
0.047058824
0.07058824
0.07450981
0.11764706
0.3137255
0.3647059
0.29411766
0.34509805
0.5058824
0.5568628
0.08235294
0.1254902
0.11372549
0.1764706
0.13333334
0.21960784
0.32941177
0.39215687
0.011764706
0.043137256
0.16078432
0.1882353
0.16470589
0.23137255
0.14901961
0.21568628
0.1254902
0.16862746
0.1882353
0.21960784
0.1764706
0.20392157
0.176

In [22]:
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
#for device in gpu_devices:
#    tf.config.experimental.set_memory_growth(device, True)
#print(labels[0])
#print(labels[330])
#print(labels[650])

In [14]:
#exp = comet_ml.Experiment(
#    api_key = API_KEY,
#    project_name = "ACloudCNN"
#)
model = generate_CNN()
model.compile(optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.build(input_shape=(None, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS))

model.summary()
checkpoint_path = "training_1/cp.ckpt.weights.h5"
checkpoint_dir = os.path.dirname(checkpoint_path)
network_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)
model.load_weights(checkpoint_path)
print(model.predict(testing_images[[1]]))
#model.fit(x=train_images, y=labels, batch_size=BATCH_SIZE, epochs=EPOCHS, callbacks=[network_callback])
print(model.predict(testing_images[[1]]))
#exp.end()

ValueError: Sequential model 'sequential_5' has already been configured to use input shape (None, 125, 125, 3). You cannot build it with input_shape (1, 125, 125, 3)

In [8]:
testing_labels2 = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES,), dtype='int64')
testing_images2 = np.zeros(shape=(TEST_IMAGE_NUMBERS * IMAGE_CATEGORIES, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS), dtype='int64')
for i in range(0, TEST_IMAGE_NUMBERS - 1):
    testing_images2[i] = (Image.open("A_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i] = 0
    testing_images2[i + TEST_IMAGE_NUMBERS] = (Image.open("B_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i + TEST_IMAGE_NUMBERS] = 1
    testing_images2[i + TEST_IMAGE_NUMBERS * 2] = (Image.open("C_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i + TEST_IMAGE_NUMBERS * 2] = 2
    testing_images2[i + TEST_IMAGE_NUMBERS * 3] = (Image.open("D_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i + TEST_IMAGE_NUMBERS * 3] = 3
    testing_images2[i + TEST_IMAGE_NUMBERS * 4] = (Image.open("E_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i + TEST_IMAGE_NUMBERS * 4] = 4
    testing_images2[i + TEST_IMAGE_NUMBERS * 5] = (Image.open("F_img" + str((i+IMAGE_NUMBERS)) + ".png")).resize((IMAGE_SIZE, IMAGE_SIZE))
    testing_labels2[i + TEST_IMAGE_NUMBERS * 5] = 5

print(Image.open("A_img" + str((i+IMAGE_Numbers))))

In [13]:
model2 = generate_CNN()
model2.compile(optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model2.build(input_shape=(None, IMAGE_SIZE, IMAGE_SIZE, IMAGE_LAYERS))
model2.load_weights(checkpoint_path)

#plt.imshow(testing_images[1])
#print(testing_images.shape)
print(model2.predict(testing_images[[1]]))
#model1.predict(testing_images[[1]])
#plt.imshow(testing_images[1])
model2.evaluate(testing_images, testing_labels)
model2.save('savedCloudModel.keras')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step
[[9.9365437e-01 3.4110933e-05 4.2883571e-06 6.3022305e-03 6.2506393e-07
  4.3881610e-06]]
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 67ms/step - accuracy: 0.8686 - loss: 0.4146
